### ISSUE TITLE
抱歉……請問一下這個插件怎麼在windows下使用呢？

### ISSUE THREAD

**Issue by 2ipm1nd** [hchunhui/librime-lua#12]
大家好，我想要試著使用這個套件來實現自動填寫當下日期，但是我跟著教學一步一步做還是沒辦法……，下面是我實作的步驟：

1. 在用戶資料夾創造一個`rime.lua`的文件(UTF-8，不帶簽名格式)，並且複製程式碼

```python
function date_translator(input, seg)
   if (input == "date") then
      --- Candidate(type, start, end, text, comment)
      yield(Candidate("date", seg.start, seg._end, os.date("%Y年%m月%d日"), " 日期"))
   end
end

function single_char_first_filter(input)
   local l = {}
   for cand in input:iter() do
      if (utf8.len(cand.text) == 1) then
         yield(cand)
      else
         table.insert(l, cand)
      end
   end
   for i, cand in ipairs(l) do
      yield(cand)
   end
end
```

2. 在`luna_pinyin_tw.custom.yaml`內放入`functions`

```yaml
patch:
  "recognizer/patterns/punct": "^/([A-Z|a-z]*|[0-9]|10)$"
  ascii_composer:
    switch_key:
      Shift_L: noop
      Shift_R: noop
  punctuator:
    import_preset: symbols
    full_shape:
      "`": "……"
    half_shape:
      "`": "……"
      "#": "#"
      "@": "@"
      "$": "$"
      "%": "%"
      "*": "*"
      "~": "~"
      "(": "("
      ")": ")"
      "_": "_"
      "/": ["、"]
    symbols:
      "/dh": ["≒","≧","≦","■","□","±","÷","×","☑"]
  translator:
    dictionary: luna_pinyin_tw.extended
  engine:
    translators:
      - lua_translator@date_translator
      - lua_translator@other_lua_function1
    filters:
      - lua_filter@single_char_first_filter
      - lua_filter@other_lua_function2

```

3. 然後重新部署

做完之後輸入date還是反應@@，請問還缺什麼步驟嗎？小狼毫的版本是0.14.2。

**Comment by hchunhui** [comment]
你好，是 `luna_pinyin_tw.custom.yaml` 的问题：

 ```yaml
patch:
  ......
  engine:
    translators:
      - lua_translator@date_translator
      - lua_translator@other_lua_function1
    filters:
      - lua_filter@single_char_first_filter
      - lua_filter@other_lua_function2
```

上面这一段配置有两个问题：
1. `other_lua_function1` 和 `other_lua_function2` 这两行不需要。`README` 这样写只是想说可以加入多个 lua 定义的函数，而此处没有定义。如只想打日期 `single_char_first_filter` 也不需要。
2. 在 patch 里面加 `translator` 的语法不对。

正确的写法类似这样：
 ```yaml
patch:
  ......
  'engine/translators/@before 0':
    lua_translator@date_translator
```
