### ISSUE TITLE
请问 comment 能放入 switches 吗？

### ISSUE THREAD

**Issue by lyserenity** [hchunhui/librime-lua#13]
例如像 sample/charset.lua 中的 charset_comment_filter，能放入 switches 切换，选择要不要显示字符集吗？如果可以的话，应该怎么写？

```
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
```
