### ISSUE TITLE
使用 lua 添加的候选词在选中后不会进入用户词表中

### ISSUE THREAD

**Issue by wudanyang6** [hchunhui/librime-lua#154]
预期：使用 lua 产生的候选词，上屏后能够进入用户词表中，同样地 input 下次要优先召回 lua 的候选词
现状：选择 lua 产生的候选词之后，用户词表中没有 lua 产生的候选词

**Comment by wudanyang6** [comment]
比如，我使用 lua 脚本在候选词尾部是 “是” 这个字时，新添加了一个候选词： 

```lua
local function add_shi(input)
   -- 使用 `iter()` 遍历所有输入候选项
   for cand in input:iter() do
      yield(cand)
      
      local newCandStr = ""
      if string.sub(cand.text, -string.len("是")) == "是" then
         newCandStr = string.gsub(cand.text, "是", "时")
         yield(Candidate("shi", cand.start, cand._end, newCandStr, cand.comment))
      end

   end
end

-- 将上述定义导出
return add_shi
```

**Comment by shewer** [comment]
code 看起來沒有問題，你的方案是如何配置的??
rime.lua   and schema

**Comment by shewer** [comment]
```lua
-- <user_data_dir>/lua/shi_add.lua 
local function add_shi(input)
   for cand in input:iter() do 
      yield(cand)

      if  cand.text:match("是$") then 
         local text =  cand.text:gsub("是$","时")  -- 替换字尾
         yield(Candidate("shi", cand.start, cand._end, text, cand.comment))
      end 
   end
end 


return shi_add
--[[
rime.lua 
shi_add= require 'shi_add'

-- schema  or  custom 
insert  "lua_filter@shi_add"   in  engine/filters    

--]]
```

**Comment by wudanyang6** [comment]
感謝您的回覆與優化代碼

在您回覆之前，經過一些配置之後，已經實現了在候選词中顯示【是不是】和【是不时】

但是，我選擇 【是不时】上屏之后，這個詞組沒有被 rime 记录，下次打 【shibushi】 還是會先出現【是不是】再出現【是不时】

補充一下我的環境：
計算機：MacBook Pro (13-inch, M1, 2020)
操作系統：macOS Big Sur 11.6.2  

rime-lua 應該沒有問題，因爲已經可以修改候選词了

rime.lua 
add_shi= require 'add_shi'

-- double_pinyin.custom.yaml
```yaml
# Rime schema
# encoding: utf-8
patch:
  schema/name: 自然码
  switches:
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: emoji_suggestion
      reset: 0
      states: [ "No", "Yes" ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: simplification
      reset: 1
      states: [ 漢字, 汉字 ]
    - name: ascii_punct
      states: [ 。，, ．， ]
  engine/translators:
    - punct_translator
    - lua_translator@date_translator
    - lua_translator@week_translator
    - lua_translator@time_translator
    - lua_translator@number_translator
    - lua_translator@reverse_lookup_filter
    - script_translator
    - table_translator@custom_phrase
  engine/filters:
    - lua_filter@add_shi
    - simplifier@emoji_suggestion
    - simplifier
    - uniquifier
    #- charset_filter@gbk
    #- single_char_filter
  engine/processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  engine/segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    # tips: all
  
  #載入朙月拼音擴充詞庫
  "translator/dictionary": luna_pinyin.extended
  'translator/preedit_format': {}
  # translator/enable_correction: true

  # 自定义符号上屏
  punctuator:
    import_preset: symbols
    # 自定义快捷符号输入
    # symbols:
    #   "/fs": [½, ‰, ¼, ⅓, ⅔, ¾, ⅒ ]
    half_shape:
      "#": "#"
      "*": "*"
      "`": "`"
      "~": "~"
      "@": "@"
      "=": "="
      "/": ["/", "÷"]
      '\': "、"
      "_" : "──"
      "'": {pair: ["「", "」"]}
      "[": "【"
      "]": "】"
      "$": ["¥", "$", "€", "£", "¢", "¤"]
      "<": ["《", "〈", "«", "<"]
      ">": ["》", "〉", "»", ">"]

  recognizer/patterns/punct: "^/([0-9]0?|[A-Za-z]+)$"

  ### 双拼使用自定义词典 custom_phrase.txt
  custom_phrase:
    dictionary: ""
    user_dict: custom_phrase
    db_class: stabledb
    enable_completion: true
    enable_sentence: true
    initial_quality: 1
  "engine/translators/@5": table_translator@custom_phrase
# Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin_flypy
# 若要启用 easy_en，取消注释下面两行
  __include: easy_en:/patch
  easy_en/enable_sentence: false # 中英文混输的设置
# Rx: lotem/rime-octagram-data:customize:schema=luna_pinyin,model=hans
  __include: grammar:/hant
# Rx: BlindingDark/rime-lua-select-character:customize:schema=luna_pinyin
  # __include: lua_select_character:/patch # 需要lua_selector打开本行注释
```
