### ISSUE TITLE
lua_filter 如何判断 cand 是否来自反查或当前是否处于反查状态？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#18]
lua_filter 基本写法都懂，只简单提示一下核心部分吧。

**Comment by hchunhui** [comment]
在 `filter` 内部好像无法判断。因为现有 librime 中实现 `translator` 没有在 cand 中留下标记；引擎本身也无“反查状态"这一概念。

但如果只是想通过输入的 pattern 决定是否执行某个 `lua_filter` 的话，是可以做到的。
方法是用 librime 引擎中的 tag 机制：

配方文本如下：
```
engine:
  ...
  filter:
    - lua_filter@func_name

...

func_name:
  tags: [ foo, bar ]
```

含义：仅当输入 segment 的 tag 为 "foo" 或 "bar" 时，此 `lua_filter` 才执行。

segment 的 tag 是由识别输入 pattern 的 `segmentor` 标上的。

---

又另：如 `lua_filter@func_name` 有多份实例，并想区别配置时，可如下：
```
...
  filter:
    - lua_filter@func_name@inst1
    - lua_filter@func_name@inst2

inst1:
  tags: ...

inst2:
  tags: ...
```

**Comment by Ace-Who** [comment]
谢谢。有个疑问，多份实例「区别配置」有何实际意义，如何体现「区别」，想不明白。例如两个实例，定义互不相交的 tags，似乎等效于单实例下定义 tags 为这两个 tags 的合并，我的测试支持这点。那么多实例能做的而单实例做不了的，应该只有多实例中各实例定义的 tags 有交集而不全同的情况了（全同等效于单实例的重复），是这样吗？

说到这里我想到可能有一个不同，是多实例可以影响候选排序，不过在我考虑的应用场景——想要区分处理 abc 和 reverse_lookup 两个 tag——多实例也影响不到排序，因为这两类候选不会共存。

如果以上理解没有错的话，解决方案还是需要写两个不同的 filter 并定义不同的 tags 了吧。

**Comment by hchunhui** [comment]
抱歉，我前面的说法可能有点误导。你分析得对，**只用来配置** tags 的时候多实例没有带来额外的功能。

tags 与多实例本身无关。我前面最后一段加上多实例的情况，只是想说清楚 `lua_filter` 会在配置文件的什么地方找 tags 。即，只有一个 “@” 时，就是以函数名为 key 在配置文件里面找；有两个 "@" 时，以第二个 "@" 后面的名字为 key 在配置文件里面找。

给实例用 "@" 起名，是 librime 的一个机制。它让每个实例可以互相区分。
比如我们在做混输或反查方案的时候，会这样做：
```
 - table_translator@foo
 - table_translator@bar

foo: ...
bar: ...
```

这样两个 `table_translator` 就会从不同的 key 里面找配置，从而表现出不同的功能。

在 lua 里面，可以用 `env.name_space` 来得到当前实例的名字，从而根据这个名字在配置文件里面找自己的配置，或者直接跟据名字走不同的分支。

突然想到，也许你的需求可以这样实现？（未测试）

配置文件：
```
- lua_filter@func_name@reverse
- lua_filter@func_name@not_reverse

reverse:
  tags: ...

not_reverse:
  tags: ...
```
lua：
```
function func_name(inp, env)
  if env.name_space == "reverse" then
   -- 反查模式
  else
   -- 正常模式
  end
end
```
