### ISSUE TITLE
可否添加一个调用 `boost::regex_search` 做正则匹配的接口

### ISSUE THREAD

**Issue by LawssssCat** [hchunhui/librime-lua#196]
配置 patterns 时发现的现象，librime 的matcher 只为首个匹配到的 pattern 添加 segment 的 tags 

```yaml
recognizer:
  patterns: 
    tag_a: ".*"
    tag_b: ".*"
```

相关代码：
1. https://github.com/rime/librime/blob/1246d21cb188e850c88d50c6e6d61e0763efd30e/src/gear/recognizer.cc#L47
2. https://github.com/rime/librime/blob/a2a6f903b042a421a73da0dfeba51028fbd8e429/src/gear/matcher.cc#L23

（要么只匹配到 tag_a, 要么只匹配到 tag_b。）**可我希望的 matcher 功能是 tag_a、tag_b 都匹配到，添加到 segment 中。**

于是用 lua_segmentor 替换 matcher

```yaml
engine:
  segmentors:
    # - matcher
    - lua_segmentor@my_matcher_segmentor
```

可这里有一个问题：
[librime 中使用 `boost::regex_search` 做正则匹配](https://github.com/rime/librime/blob/3035c2906a5bfb8487d995105c4b632d3b4ad699/src/gear/recognizer.cc#L52)。
可**lua支持的正则是不完整的**，这个匹配放到lua中执行就需要添加额外正则代码（如：[reLua](https://github.com/o080o/reLua)、[LuLPeg](https://github.com/pygy/LuLPeg)），而这些代码的正则语法又与常规的正则语法不一样。。。😥
于是又需要修改原有 `recognizer/patterns` 中的正则表达式和实现 lua 版本的 recognizer（ [recognizer 也使用 `recognizer/patterns`](https://github.com/rime/librime/blob/a2a6f903b042a421a73da0dfeba51028fbd8e429/src/gear/recognizer.cc#L87)）

😂 就很麻烦

所以能否在 librime-lua 中添加一个调用 `boost::regex_search` 做正则匹配的接口？

这样做任何正则相关的操作都能和 librime 保持一致，也省事，不需要改匹配表达式也不需要引入额外的代码
