### ISSUE TITLE
如何阻止 lua_processor 将触发按键发送出去？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#20]
套用 https://github.com/rime/librime/issues/248 的例子来说明：

```lua
-- Control+v 转大写，加空格

local function do_capital_space(s)
  return string.upper(s .. " ")
end

local function myproc(key, env)
  local engine = env.engine
  local context = engine.context
  local page_size = engine.schema.page_size

  --- accept: Control+v
  if (key:repr() == 'Control+v') then
    --- when: composing
    if (context:is_composing()) then
      local s_orig = context:get_commit_text()
      --- do_capital_space
      local s = do_capital_space(s_orig) .. ' <' .. key:repr() .. '>'
      engine:commit_text(s)
      context:clear()
      return 0 -- kAccepted
    end
  end
  return 2 -- kNoop
end

return myproc
```

方案配置：

```yaml
...
engine:
  processors:
    - ascii_composer
    - recognizer
    - lua_processor@myproc
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
...
```

使用时，在选字状态下按 <kbd>Ctrl</kbd> + <kbd>v</kbd>，成功加了空格，但是也发生了粘贴操作。又如，将按键判断改为 `key:repr() == '8'`，那么上屏时除加了空格以外，还会加个「8」。
