### ISSUE TITLE
有没有检测当前是否是ascii mode的接口？

### ISSUE THREAD

**Issue by qujihan** [hchunhui/librime-lua#265]
因为windows下没有vim mode，所以想写一个lua脚本，当按下ctrl+[，且不处于ascii mode 的时候，切换到ascii mode

请问有没有这几个接口？如果没有，还有什么曲线救国的方法嘛？

**Comment by shewer** [comment]
用key_binder 也可以
```yaml
key_binder/bindings:
     {when: always, accept: "Control+bracketleft", set_option: "ascii_mode"}
```

```lua
--  lua/keybinder.lua
local function func(key, env)
   if key:repr() == "Control+bracketleft" then
       env.engine.context:set_option("ascii_mode", true)
       return 1
    end
    return 2
end

return func
```

```yaml
# <schema>.custom.yaml
patch:
   engine/processors/@after 2: lua_processor@*keybinder
```

**Comment by qujihan** [comment]
感谢， 我这段代码进行了一些修改, 大家可以根据自己的需求去进行修改


path/to/config/lua/vim_mode.lua


```lua
-- 因为我是在win于mac上共用一套配置, mac有vim_mode, 所以不需要配置
local function is_win()
    local path_separator = package.config:sub(1, 1)
    if path_separator == '\\' then
        return true
    end
    return false
end

local function vim_mode(key, env)
    -- 如果当前是win, 且按下了ctrl+[
    if is_win() and key:repr() == "Control+bracketleft" then
        -- 检测当前是不是英文模式(其实是为了减少在win下那个 中/A 的弹窗次数)
        local get_ascii_mode = env.engine.context:get_option("ascii_mode")

        -- 如果不是英文模式, 就切换到英文模式
        if not get_ascii_mode then
            env.engine.context:set_option("ascii_mode", true)
        end

        -- 因为前面的ctrl+[ 被接管了, 所有需要发送一个ctrl+[ 给vim, 使其到normal模式
        env.engine.commit_text("Control+bracketleft")
        return 1
    end
    return 2
end

return vim_mode
```

*.schema.yaml
```yaml
engine:
  processors:
    - lua_processor@*vim_mode
    - ascii_composer
    - recognizer
    ...........
```
