### ISSUE TITLE
ShadowCandidate无法通过API修改comment

### ISSUE THREAD

**Issue by HowcanoeWang** [hchunhui/librime-lua#279]
将问题简化之后，使用下面的代码修改所有的candidate的comment，问题依然能复现：

`lua/aux_code.lua`：
```lua
local function aux_filter (input, env)
    for cand in input:iter() do
        cand.comment = '<ab>'
        yield(cand)
    end
end

return aux_filter
```

但是输入法并没有给所有的candidate都加上comment，效果如下：

![image](https://github.com/hchunhui/librime-lua/assets/19968935/a2562a6c-b9f7-4c6a-9950-e85832927c2b)

![image](https://github.com/hchunhui/librime-lua/assets/19968935/cdefaefa-616d-4b10-9898-74671d888534)

不确定是这个插件的bug还是fcitx5的性能限制，还是我打开的方式不对

---

其他的配置供参考：

`input.schema.yaml`:
```yaml
...

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - reverse_lookup_translator
    - table_translator@479k_english
    - table_translator@custom_phrase
    - table_translator@nihongo-r
    - script_translator
  filters:
    - simplifier@emoji_suggestion
    - simplifier
    - uniquifier
    - lua_filter@aux_filter
...
```

`rime.lua`:

```lua
aux_filter = require("aux_code")
```
