### ISSUE TITLE
能否调用simplifier

### ISSUE THREAD

**Issue by HowcanoeWang** [hchunhui/librime-lua#282]
目前直接在输入法中添加了日语词库，部分输入法的配置如下：

```
engine:
 ...
  translators:
    ...
    - table_translator@nihongo-r   # 日语词库
  filters:
    - simplifier@simplify
```

但全局simplifier会把日语汉字也转换成简体字。

有没有可能使用脚本，只对非日语词库的候选调用simplifier，从而解决这个问题？

**Comment by shewer** [comment]
參考 https://github.com/rime/home/issues/68
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%BA%94simplifier

感覺可以用 script_translator  +  類似 八股文 的日文  詞庫（有權 重）

**Comment by HowcanoeWang** [comment]
@shewer  抽空研究了一下，发现script_translator的方案还是有些出入。

目前主流的输入方案是，简体、繁体、日语、英语，每种都专门一个输入法，然后在输入的时候使用 ctrl+\` 进行切换。当切换到日语输入法时，会关闭繁简转换，然后再使用script_translator导入不同的假名方案和汉字方案。

但是我的做法为，直接把日语的码表挂在在了简体的下面：

> **这个是简体输入法的`scheme.yaml`文件，而不是日语输入法**
> ```
> engine:
>  ...
>   translators:
>     ...
>     - table_translator@nihongo-r   # 日语词库
>   filters:
>     - simplifier@simplify
> ```

这样的好处是不用切换输入法就能直接输入中日英(由于不同语言的输入差距，重码现象并不严重)。

但正因为使用了这个方式，才导致了简体输入法会转换日语汉字为简体。感觉还是得靠lua插件来判断字典来源，从而屏蔽日语词库的繁简转换

**Comment by shewer** [comment]
查看一下recognizer 用pattern 打tag  
把  nihongo-r:  翻譯器 打上 tag: nihongo-r
正常輸入時   segment  tags:[ abc , nihongo-r ]
當符合 nihongo-r pattern時 只剩下 tag: nihongo-r  
```yaml
abc: 
  extra_tag: [nihongo-r]  #  

nihongo-r:
tag:  nihongo-r
```

**Comment by HowcanoeWang** [comment]
感谢回复！

搜索了一下，网上的recoginzer资料似乎有点少：

* [CustomizationGuide#活用標點創建自定義詞組· rime/home Wiki](https://github.com/rime/home/wiki/CustomizationGuide#%E6%B4%BB%E7%94%A8%E6%A8%99%E9%BB%9E%E5%89%B5%E5%BB%BA%E8%87%AA%E5%AE%9A%E7%BE%A9%E8%A9%9E%E7%B5%84)
* [希望增强recognizer/patterns配置项的功能 · Issue #236 · rime/home](https://github.com/rime/home/issues/236)
* [自動識別西文及數字組成的用戶名](https://gist.github.com/lotem/3076166)

看完上述的文章，感觉和笔画反查的功能比较接近？但手动修改yaml文件还是没有什么头绪，能否麻烦提供更加详细一些的说明？

我的`schema.yaml`文件中的词库定义如下：

```
nihongo-r:
  dictionary: nihongo-r
  enable_completion: false
  enable_sentence: false
  # 尝试在这边添加tag会导致日语词库添加失败
  # tag:  nihongo-r
```

也不知道

> ```
> abc: 
>   extra_tag: [nihongo-r]  #  
> ```

这个应该具体添加到什么地方？

**Comment by shewer** [comment]
https://github.com/rime/home/wiki/Recipes#%E4%BD%BF%E7%94%A8v%E5%BF%AB%E9%80%9F%E8%BE%93%E5%85%A5%E8%8B%B1%E6%96%87

```yaml
# <方案>.custom.yaml
patch:
    abc/extra_tags: [nihongo-r]
    nihongo-r/tag: nihongo-r
    nihongo-r/prefix: "'"
    engine/segmentors/@before last:  affix_segmentor@nihongo-r # 前綴字元處理
    recognizeer/patterns/nihongo-r: "^'[a-z]*" # 首碼 ' 打上 nihongo-r

**Comment by HowcanoeWang** [comment]
尝试了很久，修改如下为能运行的一种配置（输入v开启日语模式）：

```
# mypingyin.custom.yaml

patch:   
  # 日语输入不转换为简体
  abc:
    extra_tags: [nihongo-r]

  nihongo-r:
    tag: nihongo-r
    prefix: "v"
    dictionary: nihongo-r
    tips: "〔日语输入〕"
    enable_completion: false
    enable_sentence: false

  "engine/segmentors/@before last": affix_segmentor@nihongo-r # 前綴字元處理
  "recognizer/patterns/nihongo-r": "^v[a-z]*" # 首碼 ' 打上 nihongo-r
```

```
engine:
 ...
  translators:
    ...
    - table_translator@nihongo-r   # 日语词库
  filters:
    - simplifier@simplify
    - simplifier
```
确实在日语模式下输入，但出来的还是简体字。

准备放弃了，直接alt + space切换到系统的日语输入法更快一些

感谢您的帮助与建议！

**Comment by shewer** [comment]
patterns  要設定成  唯 一   的條件，
 ^v 也可能
abc: pattern 取決於 speller  
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%80speller

如果你改成   V  可以避開  字根碼， 這也是我設置為   ‘  的原因

**Comment by HowcanoeWang** [comment]
> patterns 要設定成 唯 一 的條件，

目前我的方案里，還有/引出特殊符號，以及\`b 引出文字反查，所以暫時還不能把日语輸入设置成唯一条件

```yaml
# mypingyin.custom.yaml

patch:   
  ...
  # 扩充符号库
  punctuator/import_preset: symbols.custom
  recognizer/patterns/punct: "^/([A-Z|a-z]*|[0-9]|10)$"

  # 笔画反查
  recognizer/patterns/reverse_lookup: "`b[a-z]*'?$"
  ...
```

---

思來想去，如果能支持在lua插件里拦截simplifier/調用simiplier的話，可以把事情做的更可控一些，目前已經實現了通過translator中添加日文的comment，如果能写个filter的代碼，把備註为日文comment的candidate轉換爲simplified就完美了

```yaml
# mypingyin.schema.yaml

engine:
 ...
  translators:
    ...
    #- table_translator@nihongo-r   # 日语词库
    - lua_translator@*nihongo@nihongo-r
  filters:
    - simplifier@emoji_suggestion
    # - simplifier 
    - 
```
**配置中將simplier註釋掉，發現輸入選項里簡體和繁体混雜**

lua插件代碼：

```lua
-- nihongo.lua
NihongoTranslator={}

function NihongoTranslator.init(env)
    print( "** AuxCode filter", env.name_space )
    env.tran = Component.Translator(env.engine, "", "table_translator@" .. env.name_space)
end

function NihongoTranslator.fini(env)
end

function NihongoTranslator.func(input,seg,env)
    local t = env.tran:query(input,seg)
    for cand in t:iter() do
        cand.comment = '〔日语〕'
        -- yield(cand:to_shadow_cand("Zen",cand.text, "英文"))
        yield(cand)
    end
end

return NihongoTranslator
```

效果：

![image](https://github.com/hchunhui/librime-lua/assets/19968935/19fc826e-ef87-430a-afe3-ba0b2cc5e2b4)
