### ISSUE TITLE
能否获取当前在什么应用下嘛

### ISSUE THREAD

**Issue by Songggggr** [hchunhui/librime-lua#294]
请教下，mac 系统想获取当前在什么应用下输入
类似于 `com.microsoft.VSCode`
写了个脚本在中文输入下，输入 jj 切换成 vim normal 模式，想添加下应用限制，感谢 🙏

```lua
local function triggerEscape()
  local osascript = [[osascript -e '
     tell application "System Events" to tell front process
        key code 53
     end tell
  ']]
  os.execute(osascript)
end

local function vim_cn_jj(key, env)
  local engine = env.engine
  local context = engine.context

  if context.input == "j" and key:repr() == "j" then
    context:clear()
    triggerEscape()
    return 1
  end
  return 2
end

return vim_cn_jj
```

**Comment by oniondelta** [comment]
一個曲折的辦法！非直接獲取名稱！

於 squirrel.custom.yaml：
```yaml
patch:
  app_options:
    com.microsoft.VSCode:
      check_mode: true
```

於 xxx.schema.yaml
```yaml
switches:
  - name: check_mode
    reset: 0
```

於 lua 程式下：
```lua
local check_mode = env.engine.context:get_option("check_mode")
if check_mode then
........
end
```
