### ISSUE TITLE
config 对象是否有方法修改 __include 引用

### ISSUE THREAD

**Issue by boomker** [hchunhui/librime-lua#344]
我有一段配置，如下：

```yaml
speller:
  ...
  algebra:
    __include: algebra_xh

algebra_xh:
  ...
  - derive/^(\w)(\w)$/$1/
  ...

algebra_zrm:
  - derive/^(\w)(\w)$/$1/
  ...

```

现在的想法是在`Lua`脚本里控制 __include 不同的值，有办法实现吗？
我尝试过下面的方法：
```lua
      env:Config_set("speller/algebra/__include", "algebra_zrm")
```
发现不生效，会有报错。
@shewer ，可以指点一下吗，谢谢🙏
