### ISSUE TITLE
绑定的一对按键都会送至 processor，致使无法辨别真实按键

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#36]
通过在一个 `lua_processor@key_counter` 中将每一个按键 `key:repr()` 存入一个全局列表变量 `keys`，发现只要是被绑定的一对按键，如 `{accept: "Control+g", send: Escape, when: composing}`，按被绑的键，则两键都会依次存入 `keys`，即按 `Control+g`，就会依次存入 `Control+g`、`Escape`。方案中 `processor` 的顺序如下：

```yaml
engine:
  processors:
    - ascii_composer
    - lua_processor@key_counter
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
```

`key_counter` 在 `key_binder` 之前，怎么会收到根据后者绑定而发送的按键呢？要辨别出哪个是真实按键，有什么思路吗？我唯一的思路是读取绑定配置列表，对最近两次接收到的按键作一一比对来判断它们是不是一对绑定键。
