### ISSUE TITLE
关于打补丁的问题

### ISSUE THREAD

**Issue by gdicnng** [hchunhui/librime-lua#40]
我按说明，在 *.schema.yaml 文件里改，
　　已经弄好了，可以了。

　　就是想再问一个，如果不想在 *.schema.yaml 文件里改，想在 *.custom.yaml 文件改，应该怎样操作。
　　因为 在 *.custom.yaml 文件改，成功的话，同类型的输入法，需要相同的设置，可以直接把文件复制一下，改成另一个输入法的名字，就可以用了。而在 在 *.schema.yaml 文件里改 ，每个输入法得单独弄一下。

　　在网上搜到的方法，只能设置一条选项。
　　比如，在 *.custom.yaml 文件里这样写：
`patch:`
`  engine/translators/@next: lua_translator@date_translator`
　　这样就一条的话，可以。
　　但是如果这种写法，多于一条，前面的就无效了，
`patch:`
`  engine/translators/@next: lua_translator@date_translator`
`  engine/translators/@next: lua_translator@time_translator`
　　像上面写了两条，就最后一条才有效。
　　不怎么懂，还是在网上搜来的方法，只能单独使用其中的一条设置。
　　所以来问一下，如果在  *.custom.yaml 文件里 打补丁，需要设置这样内容不只一条，应该怎样操作？

**Comment by gdicnng** [comment]
使用的是 weasel-0.14.3.0

**Comment by hchunhui** [comment]
你找到的方法是对的，出处应该是这里： https://github.com/rime/home/wiki/CustomizationGuide
但是这种方法的问题如你所说，只能生效一个，因为 yaml 的 key-value map 不能有重复键名。

要实现多条，可参照这个文档 https://github.com/rime/home/wiki/Configuration
具体来说可以类似如下实现：
```yaml
patch:
  - engine/translators/+:
    - lua_translator@date_translator
    - lua_translator@time_translator
```
