### ISSUE TITLE
Bug 排序单字靠前时，编码少应该靠前但有问题了

### ISSUE THREAD

**Issue by nshusr** [hchunhui/librime-lua#8]
方案 https://gitee.com/xkinput/Rime_JD/

fg 为 “中国” 但 fgi 拽 却在前，请教 lua 该如何修改

![QQ图片20190617223746](https://user-images.githubusercontent.com/45023042/59612931-8bc70d00-9150-11e9-8a5e-c6df9ae6c4a4.png)

**Comment by hchunhui** [comment]
大概是在说 `sample/lua/single_char.lua` 把编码提示的候选项错误地放在前面。

`sample` 中的代码只是一个参考，用的时候一般还是看情况修改的。

以上述问题为例。编码提示候选的类型是“completion”，与普通候选的类型是不同的。
为了不让这种候选前置，可以把
```
      if (utf8.len(cand.text) == 1) then
	 yield(cand)
      else
	 table.insert(l, cand)
      end
```
改成
```
      if (utf8.len(cand.text) == 1 and cand.type ~= "completion") then
	 yield(cand)
      else
	 table.insert(l, cand)
      end
```

---
至于怎么知道“编码提示候选的类型是‘completion’”。
这是 librime 内部的约定，目前还没有文档记载。
只能通过：
1. 看 librime 的代码；
2. 用 lua 写一个 filter，将 `cand.type` 添加到注释 `cand.comment` 中，然后实验查看。

**Comment by KyleBing** [comment]
例子里写了两个方法，第二个方法不需要引入，那个是 `单字在先` 的过滤器。
只需要在对应的 `xxx.schema.yaml` 中添加第一个方法即可。

如我的五笔输入法，就是这样添加的：

```yaml
engine:
    - lua_translator@date_translator # 自定义系统变量输出
  filters:
#    - lua_filter@single_char_first_filter # 单字优先
```
